name        : libpaper
version     : 1.1.24
release     : 3
source      :
    - http://ftp.debian.org/debian/pool/main/libp/libpaper/libpaper_1.1.24+nmu2.tar.gz : c5bdd6d9dff179699160675dbb61651d9b3158f6da27558fdaba00e7c427ba96
homepage    : http://packages.qa.debian.org/libp/libpaper.html
license     :
    - GPL-2.0
summary     : Paper size library
patterns    :
    - docs:
        - /usr/share/doc
        - /usr/share/man
builddeps   :
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    libpaper is a paper library that is used to provide a simple way for applications to take actions based on specified paper sizes.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
